package it.das.travelassistant.telegram.updateshandlers.messagging;

/**
 * Created by antbucc
 */
public enum Menu {

    START,
    FROM,
    TO,
    SELEZIONE_SERVIZIO,
    EMAILCHOOSE,
    ROME2RIORESULT,
    VIAGGIATRENTOSINO,
    VIAGGIATRENTOROUTETYPE,
    VIAGGIATRENTOTRANSPORTTYPE,
    LONDONRESULT,
    VIAGGIATRENTOSTART,
    ROME2RIOAFTERCHOOSE,
    LONDONAFTERCHOOSE,
    VIAGGIATRENTODESTINATION,
    BLABLACARRESULT,
    CALCOLAROME2RIO,
    CALCOLABLABLACAR

}
